### ISSUE TITLE
Hosting on Cloud9

### ISSUE THREAD

**Issue by gnanvrath** [ConPanna/Neo4j-NodeJS-Social-Network-Videos#1]
Hi @shavit  
The videos are very helpful thank you!

I am trying to host this example on a cloud 9 ide: https://ide.c9.io/thegyani/neonodesocial

I was able to get the neo4j database up at: http://neofourjnodejs-thegyani.c9users.io:8080/browser/

therefore I set the GRAPH_DB_URL as 
http://neo4j:neo4j@neofourjnodejs-thegyani.c9users.io:8080

I am getting the error -  throw new TypeError('URL to Neo4j required'); 

I just started learning and would appreciate any help! 

Thanks and regards
Gnan

**Comment by shavit** [comment]
Hi @gnanvrath 

The port of the web interface is different from the port of the Neo4j server, as you probably noticed.

What do you get when you run `service neo4j-service status` ?

**Comment by gnanvrath** [comment]
Hi @shavit 

Thank you for a quick reply. 

Yes, used a different port as Cloud9 only opens a few ports. Had to change org.neo4j.server.webserver.port property to in 8080 (from 7474) in the  neo4j-server.properties file 

`service neo4j-service status` returns:                                                                
`neo4j-service: unrecognized service `

but `bin/neo4j` status which returns:
`Neo4j Server is running at pid 2105`

**Comment by shavit** [comment]
@gnanvrath how did you set the environment variable?

This should solve the problem, even if you use it with this fake address.
````
export GRAPH_DB_URL=http://neo4j:neo4j@0.0.0.0
````

I used [foreman](https://github.com/ddollar/foreman) to set the environment variables from a `.env` file.

**Comment by gnanvrath** [comment]
@shavit 

Tried it. Same error. 

I set the variables by entering the `export` in the terminal. 

Sorry, I feel like such a noob. My environment is [public and accessible](https://ide.c9.io/thegyani/neofourjnodejs)

**Comment by shavit** [comment]
@gnanvrath so the GraphDB is working from the web interface and you can create and delete nodes? Can you provide access? It says on C9 that it is for read only

**Comment by gnanvrath** [comment]
Hi @shavit, thank you for logging in - granted access.

Yes, the [web interface](http://neofourjnodejs-thegyani.c9users.io:8080/browser/) is working normally. 
After a long idle time, I have to run `bin/neo4j start` to get the Neo4j Server running.

**Comment by shavit** [comment]
@gnanvrath I left a file named `Neo4j.md` with short instructions how to run this. Maybe you didn't ran it from the working directory? 

Anyway, it works when you run it from the app directory. 
````
cd ~/workspace/NodeJS/Neo4j-NodeJS-Social-Network-Videos-master 
foreman start
````

Remember to edit the `.env` file and change the GraphDB URL
````
~/workspace/NodeJS/Neo4j-NodeJS-Social-Network-Videos-master/.env
````

**Comment by gnanvrath** [comment]
It works!

You are an awesome person. Thank you very much.

**Comment by shavit** [comment]
Thanks! You're welcome!
